# Generated by Django 2.1.3 on 2018-11-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(verbose_name='游戏id')),
                ('total_register', models.IntegerField(default=0, verbose_name='注册人数')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('total_male', models.IntegerField(default=0, verbose_name='男性注册人数')),
                ('total_female', models.IntegerField(default=0, verbose_name='女性注册人数')),
            ],
        ),
    ]
