# Generated by Django 2.1.3 on 2018-11-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentprovider', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='contentprovider',
            field=models.ForeignKey(default=1, on_delete='CP用户', to='contentprovider.ContentProvider'),
            preserve_default=False,
        ),
    ]
