# Generated by Django 2.1.3 on 2018-11-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_contentprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='contentprovider',
            field=models.ForeignKey(on_delete='cp名称', related_name='primary_storys', to='contentprovider.ContentProvider'),
        ),
    ]
